# Generated by Django 4.0.6 on 2022-07-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0002_alter_family_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
