# Generated by Django 4.0.6 on 2022-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0004_rename_phone_family_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
